# Generated by Django 4.1.6 on 2023-02-02 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('topic', models.CharField(choices=[('ART', 'Art'), ('CAR', 'Career'), ('COM', 'Community'), ('CUL', 'Culture'), ('ECO', 'Environmental'), ('EDU', 'Education'), ('FNC', 'Finance'), ('FOD', 'Food'), ('MED', 'Media/Pop Culture'), ('MD', 'Medical'), ('REL', 'Religion'), ('SOC', 'Social'), ('SJ', 'Social Justice'), ('SPT', 'Sports'), ('IT', 'Technology'), ('TRV', 'Travel')], max_length=3)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.profile')),
            ],
        ),
    ]
