# Generated by Django 4.1.6 on 2023-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_profile_bootcamp_grad_profile_cs_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='figma_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='google_drive_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jira_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='microsoft_teams_links',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slack_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trello_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zoom_link',
        ),
        migrations.AddField(
            model_name='project',
            name='figma_link',
            field=models.CharField(default='URL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='github_frontend_link',
            field=models.CharField(default='URL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='google_drive_link',
            field=models.CharField(default='URL1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='jira_link',
            field=models.CharField(default='URL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='microsoft_teams_links',
            field=models.CharField(default='URL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slack_link',
            field=models.CharField(default='URL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='trello_link',
            field=models.CharField(default='URL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='zoom_link',
            field=models.CharField(default='URL', max_length=200),
            preserve_default=False,
        ),
    ]
