# Generated by Django 4.1.6 on 2023-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_remove_profile_figma_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_backend_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
